services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skinemsya-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ENABLE_WEBHOOK=${ENABLE_WEBHOOK}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_ADMIN_ID=${BOT_ADMIN_ID}
      - WEBHOOK_DOMAIN=${WEBHOOK_DOMAIN}
      - DATABASE_URL=${DATABASE_URL:-file:/app/data/bot.db}
    volumes:
      - ./data:/app/data
    ports:
      - '3000:3000'

networks:
  app-network:
