services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skinemsya-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ENABLE_WEBHOOK=${ENABLE_WEBHOOK}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_ADMIN_ID=${BOT_ADMIN_ID}
      - WEBHOOK_DOMAIN=${WEBHOOK_DOMAIN}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/skinemsya?authSource=admin&directConnection=true
    networks:
      - app-network
    ports:
      - '3000:3000'

  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: unless-stopped
    # env_file:
    #   - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: >
        mongosh --quiet --eval "db.adminCommand('ping')"
        --username ${MONGO_ROOT_USER}
        --password ${MONGO_ROOT_PASSWORD}
        --authenticationDatabase admin
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network: